//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Ufal.MorphoDiTa {

public class TagsetConverter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TagsetConverter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TagsetConverter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TagsetConverter() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          morphodita_csharpPINVOKE.delete_TagsetConverter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void convert(TaggedLemma tagged_lemma) {
    morphodita_csharpPINVOKE.TagsetConverter_convert(swigCPtr, TaggedLemma.getCPtr(tagged_lemma));
    if (morphodita_csharpPINVOKE.SWIGPendingException.Pending) throw morphodita_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void convertAnalyzed(TaggedLemmas tagged_lemmas) {
    morphodita_csharpPINVOKE.TagsetConverter_convertAnalyzed(swigCPtr, TaggedLemmas.getCPtr(tagged_lemmas));
    if (morphodita_csharpPINVOKE.SWIGPendingException.Pending) throw morphodita_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void convertGenerated(TaggedLemmasForms forms) {
    morphodita_csharpPINVOKE.TagsetConverter_convertGenerated(swigCPtr, TaggedLemmasForms.getCPtr(forms));
    if (morphodita_csharpPINVOKE.SWIGPendingException.Pending) throw morphodita_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public static TagsetConverter newIdentityConverter() {
    global::System.IntPtr cPtr = morphodita_csharpPINVOKE.TagsetConverter_newIdentityConverter();
    TagsetConverter ret = (cPtr == global::System.IntPtr.Zero) ? null : new TagsetConverter(cPtr, true);
    return ret;
  }

  public static TagsetConverter newPdtToConll2009Converter() {
    global::System.IntPtr cPtr = morphodita_csharpPINVOKE.TagsetConverter_newPdtToConll2009Converter();
    TagsetConverter ret = (cPtr == global::System.IntPtr.Zero) ? null : new TagsetConverter(cPtr, true);
    return ret;
  }

  public static TagsetConverter newStripLemmaCommentConverter(Morpho dictionary) {
    global::System.IntPtr cPtr = morphodita_csharpPINVOKE.TagsetConverter_newStripLemmaCommentConverter(Morpho.getCPtr(dictionary));
    TagsetConverter ret = (cPtr == global::System.IntPtr.Zero) ? null : new TagsetConverter(cPtr, true);
    if (morphodita_csharpPINVOKE.SWIGPendingException.Pending) throw morphodita_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TagsetConverter newStripLemmaIdConverter(Morpho dictionary) {
    global::System.IntPtr cPtr = morphodita_csharpPINVOKE.TagsetConverter_newStripLemmaIdConverter(Morpho.getCPtr(dictionary));
    TagsetConverter ret = (cPtr == global::System.IntPtr.Zero) ? null : new TagsetConverter(cPtr, true);
    if (morphodita_csharpPINVOKE.SWIGPendingException.Pending) throw morphodita_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
