//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Ufal.MorphoDiTa {

public class TokenRange : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TokenRange(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TokenRange obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TokenRange() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          morphodita_csharpPINVOKE.delete_TokenRange(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint start {
    set {
      morphodita_csharpPINVOKE.TokenRange_start_set(swigCPtr, value);
    } 
    get {
      uint ret = morphodita_csharpPINVOKE.TokenRange_start_get(swigCPtr);
      return ret;
    } 
  }

  public uint length {
    set {
      morphodita_csharpPINVOKE.TokenRange_length_set(swigCPtr, value);
    } 
    get {
      uint ret = morphodita_csharpPINVOKE.TokenRange_length_get(swigCPtr);
      return ret;
    } 
  }

  public TokenRange() : this(morphodita_csharpPINVOKE.new_TokenRange(), true) {
  }

}

}
