//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Ufal.MorphoDiTa {

public class DerivationFormatter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DerivationFormatter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DerivationFormatter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DerivationFormatter() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          morphodita_csharpPINVOKE.delete_DerivationFormatter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string formatDerivation(string lemma) {
    string ret = morphodita_csharpPINVOKE.DerivationFormatter_formatDerivation(swigCPtr, lemma);
    return ret;
  }

  public static DerivationFormatter newNoneDerivationFormatter() {
    global::System.IntPtr cPtr = morphodita_csharpPINVOKE.DerivationFormatter_newNoneDerivationFormatter();
    DerivationFormatter ret = (cPtr == global::System.IntPtr.Zero) ? null : new DerivationFormatter(cPtr, true);
    return ret;
  }

  public static DerivationFormatter newRootDerivationFormatter(Derivator derinet) {
    global::System.IntPtr cPtr = morphodita_csharpPINVOKE.DerivationFormatter_newRootDerivationFormatter(Derivator.getCPtr(derinet));
    DerivationFormatter ret = (cPtr == global::System.IntPtr.Zero) ? null : new DerivationFormatter(cPtr, true);
    return ret;
  }

  public static DerivationFormatter newPathDerivationFormatter(Derivator derinet) {
    global::System.IntPtr cPtr = morphodita_csharpPINVOKE.DerivationFormatter_newPathDerivationFormatter(Derivator.getCPtr(derinet));
    DerivationFormatter ret = (cPtr == global::System.IntPtr.Zero) ? null : new DerivationFormatter(cPtr, true);
    return ret;
  }

  public static DerivationFormatter newTreeDerivationFormatter(Derivator derinet) {
    global::System.IntPtr cPtr = morphodita_csharpPINVOKE.DerivationFormatter_newTreeDerivationFormatter(Derivator.getCPtr(derinet));
    DerivationFormatter ret = (cPtr == global::System.IntPtr.Zero) ? null : new DerivationFormatter(cPtr, true);
    return ret;
  }

  public static DerivationFormatter newDerivationFormatter(string name, Derivator derinet) {
    global::System.IntPtr cPtr = morphodita_csharpPINVOKE.DerivationFormatter_newDerivationFormatter(name, Derivator.getCPtr(derinet));
    DerivationFormatter ret = (cPtr == global::System.IntPtr.Zero) ? null : new DerivationFormatter(cPtr, true);
    return ret;
  }

}

}
