//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Ufal.MorphoDiTa {

class morphodita_csharpPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="SWIGRegisterExceptionCallbacks_morphodita_csharp")]
    public static extern void SWIGRegisterExceptionCallbacks_morphodita_csharp(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_morphodita_csharp")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_morphodita_csharp(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_morphodita_csharp(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_morphodita_csharp(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(morphodita_csharpPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(morphodita_csharpPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="SWIGRegisterStringCallback_morphodita_csharp")]
    public static extern void SWIGRegisterStringCallback_morphodita_csharp(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_morphodita_csharp(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static morphodita_csharpPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_Clear")]
  public static extern void Indices_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_Add")]
  public static extern void Indices_Add(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_size")]
  public static extern uint Indices_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_capacity")]
  public static extern uint Indices_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_reserve")]
  public static extern void Indices_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_Indices__SWIG_0")]
  public static extern global::System.IntPtr new_Indices__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_Indices__SWIG_1")]
  public static extern global::System.IntPtr new_Indices__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_Indices__SWIG_2")]
  public static extern global::System.IntPtr new_Indices__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_getitemcopy")]
  public static extern int Indices_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_getitem")]
  public static extern int Indices_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_setitem")]
  public static extern void Indices_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_AddRange")]
  public static extern void Indices_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_GetRange")]
  public static extern global::System.IntPtr Indices_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_Insert")]
  public static extern void Indices_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_InsertRange")]
  public static extern void Indices_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_RemoveAt")]
  public static extern void Indices_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_RemoveRange")]
  public static extern void Indices_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_Repeat")]
  public static extern global::System.IntPtr Indices_Repeat(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_Reverse__SWIG_0")]
  public static extern void Indices_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_Reverse__SWIG_1")]
  public static extern void Indices_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_SetRange")]
  public static extern void Indices_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_Contains")]
  public static extern bool Indices_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_IndexOf")]
  public static extern int Indices_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_LastIndexOf")]
  public static extern int Indices_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Indices_Remove")]
  public static extern bool Indices_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_Indices")]
  public static extern void delete_Indices(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_Clear")]
  public static extern void Forms_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_Add")]
  public static extern void Forms_Add(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_size")]
  public static extern uint Forms_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_capacity")]
  public static extern uint Forms_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_reserve")]
  public static extern void Forms_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_Forms__SWIG_0")]
  public static extern global::System.IntPtr new_Forms__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_Forms__SWIG_1")]
  public static extern global::System.IntPtr new_Forms__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_Forms__SWIG_2")]
  public static extern global::System.IntPtr new_Forms__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_getitemcopy")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string Forms_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_getitem")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string Forms_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_setitem")]
  public static extern void Forms_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_AddRange")]
  public static extern void Forms_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_GetRange")]
  public static extern global::System.IntPtr Forms_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_Insert")]
  public static extern void Forms_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_InsertRange")]
  public static extern void Forms_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_RemoveAt")]
  public static extern void Forms_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_RemoveRange")]
  public static extern void Forms_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_Repeat")]
  public static extern global::System.IntPtr Forms_Repeat([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_Reverse__SWIG_0")]
  public static extern void Forms_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_Reverse__SWIG_1")]
  public static extern void Forms_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_SetRange")]
  public static extern void Forms_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_Contains")]
  public static extern bool Forms_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_IndexOf")]
  public static extern int Forms_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_LastIndexOf")]
  public static extern int Forms_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Forms_Remove")]
  public static extern bool Forms_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_Forms")]
  public static extern void delete_Forms(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForm_form_set")]
  public static extern void TaggedForm_form_set(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForm_form_get")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string TaggedForm_form_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForm_tag_set")]
  public static extern void TaggedForm_tag_set(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForm_tag_get")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string TaggedForm_tag_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedForm")]
  public static extern global::System.IntPtr new_TaggedForm();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_TaggedForm")]
  public static extern void delete_TaggedForm(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_Clear")]
  public static extern void TaggedForms_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_Add")]
  public static extern void TaggedForms_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_size")]
  public static extern uint TaggedForms_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_capacity")]
  public static extern uint TaggedForms_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_reserve")]
  public static extern void TaggedForms_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedForms__SWIG_0")]
  public static extern global::System.IntPtr new_TaggedForms__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedForms__SWIG_1")]
  public static extern global::System.IntPtr new_TaggedForms__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedForms__SWIG_2")]
  public static extern global::System.IntPtr new_TaggedForms__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_getitemcopy")]
  public static extern global::System.IntPtr TaggedForms_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_getitem")]
  public static extern global::System.IntPtr TaggedForms_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_setitem")]
  public static extern void TaggedForms_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_AddRange")]
  public static extern void TaggedForms_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_GetRange")]
  public static extern global::System.IntPtr TaggedForms_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_Insert")]
  public static extern void TaggedForms_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_InsertRange")]
  public static extern void TaggedForms_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_RemoveAt")]
  public static extern void TaggedForms_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_RemoveRange")]
  public static extern void TaggedForms_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_Repeat")]
  public static extern global::System.IntPtr TaggedForms_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_Reverse__SWIG_0")]
  public static extern void TaggedForms_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_Reverse__SWIG_1")]
  public static extern void TaggedForms_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedForms_SetRange")]
  public static extern void TaggedForms_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_TaggedForms")]
  public static extern void delete_TaggedForms(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemma_lemma_set")]
  public static extern void TaggedLemma_lemma_set(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemma_lemma_get")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string TaggedLemma_lemma_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemma_tag_set")]
  public static extern void TaggedLemma_tag_set(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemma_tag_get")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string TaggedLemma_tag_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedLemma")]
  public static extern global::System.IntPtr new_TaggedLemma();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_TaggedLemma")]
  public static extern void delete_TaggedLemma(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_Clear")]
  public static extern void TaggedLemmas_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_Add")]
  public static extern void TaggedLemmas_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_size")]
  public static extern uint TaggedLemmas_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_capacity")]
  public static extern uint TaggedLemmas_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_reserve")]
  public static extern void TaggedLemmas_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedLemmas__SWIG_0")]
  public static extern global::System.IntPtr new_TaggedLemmas__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedLemmas__SWIG_1")]
  public static extern global::System.IntPtr new_TaggedLemmas__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedLemmas__SWIG_2")]
  public static extern global::System.IntPtr new_TaggedLemmas__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_getitemcopy")]
  public static extern global::System.IntPtr TaggedLemmas_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_getitem")]
  public static extern global::System.IntPtr TaggedLemmas_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_setitem")]
  public static extern void TaggedLemmas_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_AddRange")]
  public static extern void TaggedLemmas_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_GetRange")]
  public static extern global::System.IntPtr TaggedLemmas_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_Insert")]
  public static extern void TaggedLemmas_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_InsertRange")]
  public static extern void TaggedLemmas_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_RemoveAt")]
  public static extern void TaggedLemmas_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_RemoveRange")]
  public static extern void TaggedLemmas_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_Repeat")]
  public static extern global::System.IntPtr TaggedLemmas_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_Reverse__SWIG_0")]
  public static extern void TaggedLemmas_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_Reverse__SWIG_1")]
  public static extern void TaggedLemmas_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmas_SetRange")]
  public static extern void TaggedLemmas_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_TaggedLemmas")]
  public static extern void delete_TaggedLemmas(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_Clear")]
  public static extern void Analyses_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_Add")]
  public static extern void Analyses_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_size")]
  public static extern uint Analyses_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_capacity")]
  public static extern uint Analyses_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_reserve")]
  public static extern void Analyses_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_Analyses__SWIG_0")]
  public static extern global::System.IntPtr new_Analyses__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_Analyses__SWIG_1")]
  public static extern global::System.IntPtr new_Analyses__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_Analyses__SWIG_2")]
  public static extern global::System.IntPtr new_Analyses__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_getitemcopy")]
  public static extern global::System.IntPtr Analyses_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_getitem")]
  public static extern global::System.IntPtr Analyses_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_setitem")]
  public static extern void Analyses_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_AddRange")]
  public static extern void Analyses_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_GetRange")]
  public static extern global::System.IntPtr Analyses_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_Insert")]
  public static extern void Analyses_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_InsertRange")]
  public static extern void Analyses_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_RemoveAt")]
  public static extern void Analyses_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_RemoveRange")]
  public static extern void Analyses_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_Repeat")]
  public static extern global::System.IntPtr Analyses_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_Reverse__SWIG_0")]
  public static extern void Analyses_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_Reverse__SWIG_1")]
  public static extern void Analyses_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Analyses_SetRange")]
  public static extern void Analyses_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_Analyses")]
  public static extern void delete_Analyses(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmaForms_lemma_set")]
  public static extern void TaggedLemmaForms_lemma_set(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmaForms_lemma_get")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string TaggedLemmaForms_lemma_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmaForms_forms_set")]
  public static extern void TaggedLemmaForms_forms_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmaForms_forms_get")]
  public static extern global::System.IntPtr TaggedLemmaForms_forms_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedLemmaForms")]
  public static extern global::System.IntPtr new_TaggedLemmaForms();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_TaggedLemmaForms")]
  public static extern void delete_TaggedLemmaForms(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_Clear")]
  public static extern void TaggedLemmasForms_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_Add")]
  public static extern void TaggedLemmasForms_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_size")]
  public static extern uint TaggedLemmasForms_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_capacity")]
  public static extern uint TaggedLemmasForms_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_reserve")]
  public static extern void TaggedLemmasForms_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedLemmasForms__SWIG_0")]
  public static extern global::System.IntPtr new_TaggedLemmasForms__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedLemmasForms__SWIG_1")]
  public static extern global::System.IntPtr new_TaggedLemmasForms__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TaggedLemmasForms__SWIG_2")]
  public static extern global::System.IntPtr new_TaggedLemmasForms__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_getitemcopy")]
  public static extern global::System.IntPtr TaggedLemmasForms_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_getitem")]
  public static extern global::System.IntPtr TaggedLemmasForms_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_setitem")]
  public static extern void TaggedLemmasForms_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_AddRange")]
  public static extern void TaggedLemmasForms_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_GetRange")]
  public static extern global::System.IntPtr TaggedLemmasForms_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_Insert")]
  public static extern void TaggedLemmasForms_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_InsertRange")]
  public static extern void TaggedLemmasForms_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_RemoveAt")]
  public static extern void TaggedLemmasForms_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_RemoveRange")]
  public static extern void TaggedLemmasForms_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_Repeat")]
  public static extern global::System.IntPtr TaggedLemmasForms_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_Reverse__SWIG_0")]
  public static extern void TaggedLemmasForms_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_Reverse__SWIG_1")]
  public static extern void TaggedLemmasForms_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TaggedLemmasForms_SetRange")]
  public static extern void TaggedLemmasForms_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_TaggedLemmasForms")]
  public static extern void delete_TaggedLemmasForms(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRange_start_set")]
  public static extern void TokenRange_start_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRange_start_get")]
  public static extern uint TokenRange_start_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRange_length_set")]
  public static extern void TokenRange_length_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRange_length_get")]
  public static extern uint TokenRange_length_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TokenRange")]
  public static extern global::System.IntPtr new_TokenRange();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_TokenRange")]
  public static extern void delete_TokenRange(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_Clear")]
  public static extern void TokenRanges_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_Add")]
  public static extern void TokenRanges_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_size")]
  public static extern uint TokenRanges_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_capacity")]
  public static extern uint TokenRanges_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_reserve")]
  public static extern void TokenRanges_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TokenRanges__SWIG_0")]
  public static extern global::System.IntPtr new_TokenRanges__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TokenRanges__SWIG_1")]
  public static extern global::System.IntPtr new_TokenRanges__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_TokenRanges__SWIG_2")]
  public static extern global::System.IntPtr new_TokenRanges__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_getitemcopy")]
  public static extern global::System.IntPtr TokenRanges_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_getitem")]
  public static extern global::System.IntPtr TokenRanges_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_setitem")]
  public static extern void TokenRanges_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_AddRange")]
  public static extern void TokenRanges_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_GetRange")]
  public static extern global::System.IntPtr TokenRanges_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_Insert")]
  public static extern void TokenRanges_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_InsertRange")]
  public static extern void TokenRanges_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_RemoveAt")]
  public static extern void TokenRanges_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_RemoveRange")]
  public static extern void TokenRanges_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_Repeat")]
  public static extern global::System.IntPtr TokenRanges_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_Reverse__SWIG_0")]
  public static extern void TokenRanges_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_Reverse__SWIG_1")]
  public static extern void TokenRanges_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TokenRanges_SetRange")]
  public static extern void TokenRanges_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_TokenRanges")]
  public static extern void delete_TokenRanges(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemma_lemma_set")]
  public static extern void DerivatedLemma_lemma_set(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemma_lemma_get")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string DerivatedLemma_lemma_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_DerivatedLemma")]
  public static extern global::System.IntPtr new_DerivatedLemma();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_DerivatedLemma")]
  public static extern void delete_DerivatedLemma(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_Clear")]
  public static extern void DerivatedLemmas_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_Add")]
  public static extern void DerivatedLemmas_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_size")]
  public static extern uint DerivatedLemmas_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_capacity")]
  public static extern uint DerivatedLemmas_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_reserve")]
  public static extern void DerivatedLemmas_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_DerivatedLemmas__SWIG_0")]
  public static extern global::System.IntPtr new_DerivatedLemmas__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_DerivatedLemmas__SWIG_1")]
  public static extern global::System.IntPtr new_DerivatedLemmas__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_DerivatedLemmas__SWIG_2")]
  public static extern global::System.IntPtr new_DerivatedLemmas__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_getitemcopy")]
  public static extern global::System.IntPtr DerivatedLemmas_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_getitem")]
  public static extern global::System.IntPtr DerivatedLemmas_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_setitem")]
  public static extern void DerivatedLemmas_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_AddRange")]
  public static extern void DerivatedLemmas_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_GetRange")]
  public static extern global::System.IntPtr DerivatedLemmas_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_Insert")]
  public static extern void DerivatedLemmas_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_InsertRange")]
  public static extern void DerivatedLemmas_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_RemoveAt")]
  public static extern void DerivatedLemmas_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_RemoveRange")]
  public static extern void DerivatedLemmas_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_Repeat")]
  public static extern global::System.IntPtr DerivatedLemmas_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_Reverse__SWIG_0")]
  public static extern void DerivatedLemmas_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_Reverse__SWIG_1")]
  public static extern void DerivatedLemmas_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivatedLemmas_SetRange")]
  public static extern void DerivatedLemmas_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_DerivatedLemmas")]
  public static extern void delete_DerivatedLemmas(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Version_major_set")]
  public static extern void Version_major_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Version_major_get")]
  public static extern uint Version_major_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Version_minor_set")]
  public static extern void Version_minor_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Version_minor_get")]
  public static extern uint Version_minor_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Version_patch_set")]
  public static extern void Version_patch_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Version_patch_get")]
  public static extern uint Version_patch_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Version_prerelease_set")]
  public static extern void Version_prerelease_set(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Version_prerelease_get")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string Version_prerelease_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Version_current")]
  public static extern global::System.IntPtr Version_current();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_new_Version")]
  public static extern global::System.IntPtr new_Version();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_Version")]
  public static extern void delete_Version(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_Tokenizer")]
  public static extern void delete_Tokenizer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tokenizer_setText")]
  public static extern void Tokenizer_setText(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tokenizer_nextSentence")]
  public static extern bool Tokenizer_nextSentence(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tokenizer_newVerticalTokenizer")]
  public static extern global::System.IntPtr Tokenizer_newVerticalTokenizer();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tokenizer_newCzechTokenizer")]
  public static extern global::System.IntPtr Tokenizer_newCzechTokenizer();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tokenizer_newEnglishTokenizer")]
  public static extern global::System.IntPtr Tokenizer_newEnglishTokenizer();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tokenizer_newGenericTokenizer")]
  public static extern global::System.IntPtr Tokenizer_newGenericTokenizer();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_Derivator")]
  public static extern void delete_Derivator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Derivator_parent")]
  public static extern bool Derivator_parent(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Derivator_children")]
  public static extern bool Derivator_children(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_DerivationFormatter")]
  public static extern void delete_DerivationFormatter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivationFormatter_formatDerivation")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string DerivationFormatter_formatDerivation(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivationFormatter_newNoneDerivationFormatter")]
  public static extern global::System.IntPtr DerivationFormatter_newNoneDerivationFormatter();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivationFormatter_newRootDerivationFormatter")]
  public static extern global::System.IntPtr DerivationFormatter_newRootDerivationFormatter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivationFormatter_newPathDerivationFormatter")]
  public static extern global::System.IntPtr DerivationFormatter_newPathDerivationFormatter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivationFormatter_newTreeDerivationFormatter")]
  public static extern global::System.IntPtr DerivationFormatter_newTreeDerivationFormatter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_DerivationFormatter_newDerivationFormatter")]
  public static extern global::System.IntPtr DerivationFormatter_newDerivationFormatter([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_Morpho")]
  public static extern void delete_Morpho(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Morpho_load")]
  public static extern global::System.IntPtr Morpho_load([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Morpho_NO_GUESSER_get")]
  public static extern int Morpho_NO_GUESSER_get();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Morpho_GUESSER_get")]
  public static extern int Morpho_GUESSER_get();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Morpho_analyze")]
  public static extern int Morpho_analyze(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2, int jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Morpho_generate")]
  public static extern int Morpho_generate(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg3, int jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Morpho_rawLemma")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string Morpho_rawLemma(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Morpho_lemmaId")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string Morpho_lemmaId(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Morpho_rawForm")]
  [return: global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]
  public static extern string Morpho_rawForm(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Morpho_newTokenizer")]
  public static extern global::System.IntPtr Morpho_newTokenizer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Morpho_getDerivator")]
  public static extern global::System.IntPtr Morpho_getDerivator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_Tagger")]
  public static extern void delete_Tagger(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tagger_load")]
  public static extern global::System.IntPtr Tagger_load([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(UTF8Marshaler))]string jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tagger_getMorpho")]
  public static extern global::System.IntPtr Tagger_getMorpho(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tagger_tag__SWIG_0")]
  public static extern void Tagger_tag__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tagger_tag__SWIG_1")]
  public static extern void Tagger_tag__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tagger_tagAnalyzed")]
  public static extern void Tagger_tagAnalyzed(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_Tagger_newTokenizer")]
  public static extern global::System.IntPtr Tagger_newTokenizer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_delete_TagsetConverter")]
  public static extern void delete_TagsetConverter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TagsetConverter_convert")]
  public static extern void TagsetConverter_convert(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TagsetConverter_convertAnalyzed")]
  public static extern void TagsetConverter_convertAnalyzed(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TagsetConverter_convertGenerated")]
  public static extern void TagsetConverter_convertGenerated(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TagsetConverter_newIdentityConverter")]
  public static extern global::System.IntPtr TagsetConverter_newIdentityConverter();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TagsetConverter_newPdtToConll2009Converter")]
  public static extern global::System.IntPtr TagsetConverter_newPdtToConll2009Converter();

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TagsetConverter_newStripLemmaCommentConverter")]
  public static extern global::System.IntPtr TagsetConverter_newStripLemmaCommentConverter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("morphodita_csharp", EntryPoint="CSharp_TagsetConverter_newStripLemmaIdConverter")]
  public static extern global::System.IntPtr TagsetConverter_newStripLemmaIdConverter(global::System.Runtime.InteropServices.HandleRef jarg1);

public class UTF8Marshaler : System.Runtime.InteropServices.ICustomMarshaler {
    static UTF8Marshaler static_instance;

    public System.IntPtr MarshalManagedToNative(object managedObj) {
        if (managedObj == null)
            return System.IntPtr.Zero;
        if (!(managedObj is string))
            throw new System.Runtime.InteropServices.MarshalDirectiveException("UTF8Marshaler must be used on a string.");

        // not null terminated
        byte[] strbuf = System.Text.Encoding.UTF8.GetBytes((string)managedObj);
        System.IntPtr buffer = System.Runtime.InteropServices.Marshal.AllocHGlobal(strbuf.Length + 1);
        System.Runtime.InteropServices.Marshal.Copy(strbuf, 0, buffer, strbuf.Length);

        // write the terminating null
        System.Runtime.InteropServices.Marshal.WriteByte(buffer + strbuf.Length, 0);
        return buffer;
    }

    public object MarshalNativeToManaged(System.IntPtr pNativeData) {
        int length = 0;
        while (System.Runtime.InteropServices.Marshal.ReadByte(pNativeData, length) != 0)
            length++;

        // should not be null terminated
        byte[] strbuf = new byte[length];
        // skip the trailing null
        System.Runtime.InteropServices.Marshal.Copy((System.IntPtr)pNativeData, strbuf, 0, length);
        string data = System.Text.Encoding.UTF8.GetString(strbuf);
        return data;
    }

    public void CleanUpNativeData(System.IntPtr pNativeData) {
        System.Runtime.InteropServices.Marshal.FreeHGlobal(pNativeData);
    }

    public void CleanUpManagedData(object managedObj) {
    }

    public int GetNativeDataSize() {
        return -1;
    }

    public static System.Runtime.InteropServices.ICustomMarshaler GetInstance(string cookie) {
        if (static_instance == null)
            return static_instance = new UTF8Marshaler();
        return static_instance;
    }
}

}

}
